// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLRhcfizlyhGGEg6v-tw2VDE4DEkrPiBw',
    appId: '1:52442332602:web:1dc5f49f41a8bb53c6f183',
    messagingSenderId: '52442332602',
    projectId: 'chat-app-flutter-e3ac4',
    authDomain: 'chat-app-flutter-e3ac4.firebaseapp.com',
    storageBucket: 'chat-app-flutter-e3ac4.appspot.com',
    measurementId: 'G-0ZTH8B98P9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsShn8OwL2ITG8grTJCgtmmu59yshw5Wg',
    appId: '1:52442332602:android:7347802f2ad8d9b7c6f183',
    messagingSenderId: '52442332602',
    projectId: 'chat-app-flutter-e3ac4',
    storageBucket: 'chat-app-flutter-e3ac4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDh-XqUrh9e2UT3E5LTFKJxzSlzmdPsdT0',
    appId: '1:52442332602:ios:cd7d12bab3b14f01c6f183',
    messagingSenderId: '52442332602',
    projectId: 'chat-app-flutter-e3ac4',
    storageBucket: 'chat-app-flutter-e3ac4.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDh-XqUrh9e2UT3E5LTFKJxzSlzmdPsdT0',
    appId: '1:52442332602:ios:361dab94c7bc6e0bc6f183',
    messagingSenderId: '52442332602',
    projectId: 'chat-app-flutter-e3ac4',
    storageBucket: 'chat-app-flutter-e3ac4.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
